name: flutter_klaviyo
description: Klaviyo flutter plugin
version: 0.2.1
homepage: https://github.com/derhub/flutter_klaviyo

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterKlaviyoPlugin
