name: flutter_klaviyo
description: Klaviyo flutter plugin
version: 0.2.1
author: derhub
homepage: https://github.com/derhub/flutter_klaviyo

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ^2.0.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.derhub.flutter_klaviyo
        pluginClass: FlutterKlaviyoPlugin
      ios:
        pluginClass: FlutterKlaviyoPlugin