name: Main Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Install Flutter
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "1.22.x"

      - name: Versions
      - run: dart --version
      - run: flutter --version

      - name: Install dependencies
      - run: flutter pub get

      - name: Test app
      - run: flutter test
